# Site settings
title: Music Encoding Initiative
email: info@music-encoding.org
baseurl: "" 
url: "http://music-encoding.org" # the base hostname & protocol for your site
twitter_username: music-encoding

# Build settings
markdown: kramdown
